// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func UniqueSellingPoints() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"unique-selling-points\"><h2 class=\"unique-selling-points__title\">\"Alright... But what sets you apart?\"</h2><div class=\"usp-grid\"><div class=\"usp-item\"><h3 class=\"usp-item__title\">Lifetime Guarantee</h3><p class=\"usp-item__description\">I provide a Certificate of Authenticity (COA) with each photograph, ensuring its limited edition, numbered status, and museum-grade longevity. These aren't just pictures—they're investments.</p></div><div class=\"usp-item\"><h3 class=\"usp-item__title\">Craftsmanship</h3><p class=\"usp-item__description\">Each photograph is a one-of-a-kind, high-quality, handmade artwork, crafted with specialized knowledge and years of experience. No Photoshop. No AI.</p></div><div class=\"usp-item\"><h3 class=\"usp-item__title\">Local</h3><p class=\"usp-item__description\">I am not hidden away in some anonymous location. My photos are taken right here in our neighbourhood. As a local company, you can easily reach me whenever you need.</p></div><div class=\"usp-item\"><h3 class=\"usp-item__title\">Specialization</h3><p class=\"usp-item__description\">A man of many talents... but master of none. Expertise drives success. That is why I focus on the industries I know, to guarantee results.</p></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
