// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TopBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"topbar\"><div class=\"topbar__container\"><a href=\"/\" class=\"topbar__logo\"><img src=\"/static/images/loubna-photo-logo.svg\" alt=\"Loubna Photo\" class=\"topbar__logo-image\"></a><nav class=\"topbar__nav\"><ul class=\"topbar__nav-list\"><li class=\"topbar__nav-item\"><a href=\"/\" class=\"topbar__nav-link\">Home</a></li><li class=\"topbar__nav-item\"><a href=\"/about\" class=\"topbar__nav-link\">About</a></li><li class=\"topbar__nav-item\"><a href=\"/gallery\" class=\"topbar__nav-link\">Gallery</a></li><li class=\"topbar__nav-item\"><a href=\"/contact\" class=\"topbar__nav-link\">Contact</a></li></ul></nav></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
